"""
AI explanation layer. Takes the DETERMINISTIC facts from analyzer.py
and asks Claude to explain the module in plain English, citing the
actual facts found - never inventing behavior the static analysis
didn't observe. If no API key is present, uses an honestly-labeled
mock so the tool is still runnable and truthful about what's real.
"""
import os

try:
    import anthropic
    HAS_SDK = True
except ImportError:
    HAS_SDK = False


def _build_prompt(facts, source_snippet):
    return f"""You are analyzing an undocumented legacy code module for a
modernization assessment. Use ONLY the facts and code below - do not
invent behavior. If something is genuinely ambiguous, say so explicitly
rather than guessing confidently.

Module: {facts.name}
Functions found: {facts.functions}
Cross-module imports: {facts.imports_from}
Magic numbers found (undocumented constants): {facts.magic_numbers}
Branch/conditional count: {facts.branch_count}
Bare except (swallows errors silently): {facts.has_bare_except}
TODO/warning comments found: {facts.todo_comments}

Source:
{source_snippet}

Respond in this exact format:
SUMMARY: <2-3 plain English sentences on what this module does>
RISKS: <bullet list of specific ambiguous or risky behaviors, citing line evidence>
UNCERTAIN_ABOUT: <what you genuinely cannot determine from this code alone>
"""


def explain_module(facts, source_snippet, api_key=None, model="claude-sonnet-4-6"):
    api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")

    if not api_key or not HAS_SDK:
        return _mock_explain(facts)

    client = anthropic.Anthropic(api_key=api_key)
    prompt = _build_prompt(facts, source_snippet)
    resp = client.messages.create(
        model=model,
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(b.text for b in resp.content if b.type == "text")
    return {"source": "live_claude_api", "text": text}


def _mock_explain(facts):
    """Honest stand-in: shows exactly what WOULD be sent and a realistic
    shape of response, clearly labeled as not a real API call."""
    return {
        "source": "MOCK - no ANTHROPIC_API_KEY present, this is illustrative only",
        "text": (
            f"SUMMARY: [Would be generated by Claude from the {len(facts.functions)} "
            f"functions and {len(facts.magic_numbers)} undocumented constants found in "
            f"{facts.name}.]\n"
            f"RISKS: [Would cite the specific magic numbers {facts.magic_numbers} and "
            f"flag the bare except ({facts.has_bare_except}) as silently hiding failures.]\n"
            f"UNCERTAIN_ABOUT: [Would flag the TODO comments as unresolved business logic "
            f"risk: {facts.todo_comments}]"
        ),
    }
